// formater data for put request
export const createUserData = (data, permissions) => {
  return {
    email: data.email,
    username: data.email,
    profile_data: {
      name: data.name,
      island: data.island,
      surname: data.surname,
      birthdate: data.birthdate,
      occupation: data.occupation,
      birth_place: data.birth_place,
      father_name: data.father_name,
      mother_name: data.mother_name,
      postal_code: data.postal_code,
      current_city: data.current_city,
      other_groups: data.other_groups,
      phone_number: data.phone_number,
      current_street: data.current_street,
      father_surname: data.father_surname,
      mother_surname: data.mother_surname,
      current_country: data.current_country,
      dimotiki_enotita: data.dimotiki_enotita,
      permissions: {
        email: permissions.email,
        username: permissions.username,
        profile_data: {
          name: permissions.name,
          island: permissions.island,
          surname: permissions.surname,
          birthdate: permissions.birthdate,
          occupation: permissions.occupation,
          birth_place: permissions.birth_place,
          father_name: permissions.father_name,
          mother_name: permissions.mother_name,
          postal_code: permissions.postal_code,
          current_city: permissions.current_city,
          other_groups: permissions.other_groups,
          phone_number: permissions.phone_number,
          current_street: permissions.current_street,
          father_surname: permissions.father_surname,
          mother_surname: permissions.mother_surname,
          current_country: permissions.current_country,
          dimotiki_enotita: permissions.dimotiki_enotita,
        },
      },
    },
  };
};
